import type {
  AIHotspot,
  AuditLog,
  Camp,
  DistrictKPI,
  EMR,
  Patient,
  Referral,
  ReferralPriority,
  ScreeningTeam,
  SpectacleOrder,
  StateKPIs,
  TeleconsultSession,
  User,
  Vendor,
} from "./types";

export const stateKPIs: StateKPIs = {
  totalScreened: 2847563,
  totalSpectacles: 892341,
  totalReferrals: 45678,
  slaBreaches: 234,
  activeCamps: 142,
  completedCamps: 3891,
  teleconsultSessions: 12456,
  abhaLinked: 2156789,
};

export const districtKPIs: DistrictKPI[] = [
  {
    district: "Visakhapatnam",
    screened: 312456,
    target: 210000,
    spectacles: 98432,
    referrals: 5234,
    slaBreaches: 18,
    camps: 48,
    lat: 17.6868,
    lng: 83.2185,
    diseaseBurden: 72,
  },
  {
    district: "Guntur",
    screened: 198450,
    target: 220000,
    spectacles: 45600,
    referrals: 3580,
    slaBreaches: 9,
    camps: 42,
    lat: 16.3067,
    lng: 80.4365,
    diseaseBurden: 68,
  },
  {
    district: "Krishna",
    screened: 265432,
    target: 185000,
    spectacles: 81234,
    referrals: 4123,
    slaBreaches: 15,
    camps: 38,
    lat: 16.5062,
    lng: 80.648,
    diseaseBurden: 65,
  },
  {
    district: "East Godavari",
    screened: 298765,
    target: 195000,
    spectacles: 92345,
    referrals: 5012,
    slaBreaches: 28,
    camps: 45,
    lat: 17.0005,
    lng: 81.804,
    diseaseBurden: 74,
  },
  {
    district: "West Godavari",
    screened: 245678,
    target: 175000,
    spectacles: 76543,
    referrals: 3876,
    slaBreaches: 12,
    camps: 35,
    lat: 16.9174,
    lng: 81.3399,
    diseaseBurden: 61,
  },
  {
    district: "Chittoor",
    screened: 234567,
    target: 180000,
    spectacles: 72345,
    referrals: 3654,
    slaBreaches: 19,
    camps: 33,
    lat: 13.2172,
    lng: 79.1003,
    diseaseBurden: 58,
  },
  {
    district: "Kurnool",
    screened: 256789,
    target: 195000,
    spectacles: 78901,
    referrals: 3987,
    slaBreaches: 24,
    camps: 36,
    lat: 15.8281,
    lng: 78.0373,
    diseaseBurden: 70,
  },
  {
    district: "Anantapur",
    screened: 223456,
    target: 200000,
    spectacles: 69876,
    referrals: 3456,
    slaBreaches: 16,
    camps: 31,
    lat: 14.6819,
    lng: 77.6006,
    diseaseBurden: 63,
  },
  {
    district: "Nellore",
    screened: 212345,
    target: 150000,
    spectacles: 65432,
    referrals: 3234,
    slaBreaches: 14,
    camps: 29,
    lat: 14.4426,
    lng: 79.9865,
    diseaseBurden: 55,
  },
  {
    district: "Prakasam",
    screened: 198765,
    target: 165000,
    spectacles: 61234,
    referrals: 2987,
    slaBreaches: 11,
    camps: 27,
    lat: 15.5057,
    lng: 80.0499,
    diseaseBurden: 52,
  },
  {
    district: "Kadapa",
    screened: 187654,
    target: 145000,
    spectacles: 58765,
    referrals: 2765,
    slaBreaches: 13,
    camps: 25,
    lat: 14.4673,
    lng: 78.8242,
    diseaseBurden: 59,
  },
  {
    district: "Srikakulam",
    screened: 176543,
    target: 150000,
    spectacles: 54321,
    referrals: 2543,
    slaBreaches: 9,
    camps: 23,
    lat: 18.2949,
    lng: 83.8935,
    diseaseBurden: 48,
  },
  {
    district: "Vizianagaram",
    screened: 165432,
    target: 140000,
    spectacles: 51234,
    referrals: 2345,
    slaBreaches: 8,
    camps: 22,
    lat: 18.1067,
    lng: 83.3956,
    diseaseBurden: 46,
  },
];

export const monthlyScreeningTrend = [
  { month: "Jul", screened: 198000, spectacles: 62000, referrals: 3200 },
  { month: "Aug", screened: 215000, spectacles: 68000, referrals: 3500 },
  { month: "Sep", screened: 232000, spectacles: 72000, referrals: 3800 },
  { month: "Oct", screened: 248000, spectacles: 76000, referrals: 4100 },
  { month: "Nov", screened: 265000, spectacles: 81000, referrals: 4300 },
  { month: "Dec", screened: 278000, spectacles: 85000, referrals: 4500 },
  { month: "Jan", screened: 290000, spectacles: 89000, referrals: 4700 },
];

export const diseaseHotspots = [
  {
    village: "Anakapalle",
    district: "Visakhapatnam",
    drCases: 234,
    myopiaCases: 567,
    lat: 17.691,
    lng: 83.0036,
  },
  {
    village: "Tenali",
    district: "Guntur",
    drCases: 198,
    myopiaCases: 489,
    lat: 16.2428,
    lng: 80.64,
  },
  {
    village: "Machilipatnam",
    district: "Krishna",
    drCases: 176,
    myopiaCases: 423,
    lat: 16.1875,
    lng: 81.1389,
  },
  {
    village: "Rajahmundry",
    district: "East Godavari",
    drCases: 212,
    myopiaCases: 534,
    lat: 17.0005,
    lng: 81.804,
  },
  {
    village: "Tirupati",
    district: "Chittoor",
    drCases: 156,
    myopiaCases: 398,
    lat: 13.6288,
    lng: 79.4192,
  },
];

export const camps: Camp[] = [
  {
    id: "CMP-3401",
    name: "Mangalagiri PHC Camp",
    type: "village",
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Mangalagiri",
    lat: 16.4307,
    lng: 80.568,
    scheduledDate: "2026-06-11",
    teamId: "TM-12",
    teamName: "Guntur Team Alpha",
    nodalOfficerId: "NO-02",
    status: "active",
    patientCount: 80,
    screenedCount: 34,
  },
  {
    id: "CMP-3402",
    name: "Tadepalli ZP School",
    type: "school",
    district: "Guntur",
    mandal: "Tadepalli",
    village: "Tadepalli",
    lat: 16.48,
    lng: 80.6,
    scheduledDate: "2026-06-11",
    teamId: "TM-13",
    teamName: "Guntur Team Bravo",
    nodalOfficerId: "NO-02",
    status: "active",
    patientCount: 220,
    screenedCount: 95,
  },
  {
    id: "CMP-3403",
    name: "Araku Tribal Camp",
    type: "tribal",
    district: "Visakhapatnam",
    mandal: "Araku Valley",
    village: "Araku",
    lat: 18.3273,
    lng: 82.8763,
    scheduledDate: "2026-06-12",
    teamId: "TM-21",
    teamName: "Vizag Team Tribal",
    nodalOfficerId: "NO-01",
    status: "scheduled",
    patientCount: 150,
    screenedCount: 0,
  },
  {
    id: "CMP-3404",
    name: "Gajuwaka Urban Slum",
    type: "urban_slum",
    district: "Visakhapatnam",
    mandal: "Gajuwaka",
    village: "Gajuwaka",
    lat: 17.6889,
    lng: 83.2099,
    scheduledDate: "2026-06-10",
    teamId: "TM-22",
    teamName: "Vizag Team Coastal",
    nodalOfficerId: "NO-01",
    status: "completed",
    patientCount: 200,
    screenedCount: 200,
  },
  {
    id: "CMP-3405",
    name: "Anantapur Industrial Estate",
    type: "industrial",
    district: "Anantapur",
    mandal: "Anantapur Urban",
    village: "Industrial Estate",
    lat: 14.6819,
    lng: 77.6006,
    scheduledDate: "2026-06-13",
    teamId: "TM-31",
    teamName: "Anantapur Team One",
    nodalOfficerId: "NO-06",
    status: "scheduled",
    patientCount: 160,
    screenedCount: 0,
  },
  {
    id: "CMP-3406",
    name: "Kurnool Rural PHC",
    type: "village",
    district: "Kurnool",
    mandal: "Kallur",
    village: "Kallur",
    lat: 15.8281,
    lng: 78.0373,
    scheduledDate: "2026-06-11",
    teamId: "TM-41",
    teamName: "Kurnool Team One",
    nodalOfficerId: "NO-07",
    status: "active",
    patientCount: 190,
    screenedCount: 78,
  },
  {
    id: "CMP-3407",
    name: "Rajahmundry City School",
    type: "school",
    district: "East Godavari",
    mandal: "Rajahmundry",
    village: "Rajahmundry",
    lat: 17.0005,
    lng: 81.804,
    scheduledDate: "2026-06-09",
    teamId: "TM-51",
    teamName: "EG Team One",
    nodalOfficerId: "NO-04",
    status: "completed",
    patientCount: 240,
    screenedCount: 240,
  },
  {
    id: "CMP-3408",
    name: "Ongole Village Outreach",
    type: "village",
    district: "Prakasam",
    mandal: "Ongole",
    village: "Throvagunta",
    lat: 15.5057,
    lng: 80.0499,
    scheduledDate: "2026-06-12",
    teamId: "TM-61",
    teamName: "Prakasam Team One",
    nodalOfficerId: "NO-11",
    status: "scheduled",
    patientCount: 170,
    screenedCount: 0,
  },
  {
    id: "CMP-3409",
    name: "Tirupati Urban Camp",
    type: "urban_slum",
    district: "Chittoor",
    mandal: "Tirupati Urban",
    village: "Tirupati",
    lat: 13.6288,
    lng: 79.4192,
    scheduledDate: "2026-06-11",
    teamId: "TM-71",
    teamName: "Chittoor Team One",
    nodalOfficerId: "NO-08",
    status: "active",
    patientCount: 210,
    screenedCount: 134,
  },
  {
    id: "CMP-3410",
    name: "Kakinada Coastal Camp",
    type: "village",
    district: "East Godavari",
    mandal: "Kakinada Rural",
    village: "Sarpavaram",
    lat: 16.9891,
    lng: 82.2475,
    scheduledDate: "2026-06-14",
    teamId: "TM-52",
    teamName: "EG Team Two",
    nodalOfficerId: "NO-04",
    status: "scheduled",
    patientCount: 180,
    screenedCount: 0,
  },
];

export const patients: Patient[] = [
  {
    id: "pat-001",
    abhaNumber: "91-1234-5678-9012",
    mobile: "9876543210",
    name: "Rama Rao",
    age: 45,
    gender: "Male",
    district: "Visakhapatnam",
    mandal: "Anakapalle",
    village: "Anakapalle",
  },
  {
    id: "pat-002",
    abhaNumber: "91-2345-6789-0123",
    mobile: "9876543211",
    name: "Lakshmi Devi",
    age: 38,
    gender: "Female",
    district: "Visakhapatnam",
    mandal: "Anakapalle",
    village: "Kasimkota",
  },
  {
    id: "pat-003",
    mobile: "9876543212",
    name: "Venkat Reddy",
    age: 62,
    gender: "Male",
    district: "Visakhapatnam",
    mandal: "Anakapalle",
    village: "Nakkapalle",
  },
  {
    id: "pat-004",
    abhaNumber: "91-3456-7890-1234",
    mobile: "9876543213",
    name: "Sita Kumari",
    age: 28,
    gender: "Female",
    district: "Guntur",
    mandal: "Tenali",
    village: "Tenali",
  },
  {
    id: "pat-005",
    mobile: "9876543214",
    name: "Krishna Murthy",
    age: 55,
    gender: "Male",
    district: "Krishna",
    mandal: "Vijayawada",
    village: "One Town",
  },
  {
    id: "p001",
    abhaNumber: "91-1234-5678-9012",
    name: "Ravi Kumar",
    age: 42,
    gender: "Male",
    mobile: "9876543210",
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Pedakurapadu",
    campId: "CMP-3401",
    status: "Submitted",
    registeredAt: "2024-06-10T09:30:00",
  },
  {
    id: "p002",
    abhaNumber: "91-2345-6789-0123",
    name: "Lakshmi Devi",
    age: 58,
    gender: "Female",
    mobile: "9876543211",
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Krosuru",
    campId: "CMP-3401",
    status: "Submitted",
    registeredAt: "2024-06-10T09:45:00",
  },
  {
    id: "p003",
    name: "Suresh Babu",
    age: 35,
    gender: "Male",
    mobile: "9876543212",
    district: "Guntur",
    mandal: "Mangalagiri",
    village: "Mangalagiri Town",
    campId: "CMP-3401",
    status: "EMR Done",
    registeredAt: "2024-06-10T10:00:00",
  },
  {
    id: "p006",
    abhaNumber: "91-4567-8901-2345",
    name: "Anitha Kumari",
    age: 29,
    gender: "Female",
    mobile: "9876543215",
    district: "Guntur",
    mandal: "Tenali",
    village: "Kolakaluru",
    campId: "CMP-3401",
    status: "Registered",
    registeredAt: "2024-06-10T11:30:00",
  },
  {
    id: "p011",
    name: "Bhaskar Rao",
    age: 52,
    gender: "Male",
    mobile: "9876543220",
    district: "Guntur",
    mandal: "Bapatla",
    village: "Chirala Road",
    campId: "CMP-3401",
    status: "Registered",
    registeredAt: "2024-06-10T12:00:00",
  },
];

export const emrs: EMR[] = [
  {
    id: "emr-001",
    patientId: "pat-001",
    patientName: "Rama Rao",
    campId: "CMP-3401",
    campName: "Mangalagiri PHC Camp",
    screeningTeamId: "TM-12",
    screeningTeamName: "Guntur Team Alpha",
    district: "Guntur",
    diminishedVisionDistance: true,
    diminishedVisionNear: false,
    redness: false,
    watering: false,
    pain: false,
    blurredVision: true,
    photophobia: false,
    flashersFloaters: false,
    diplopia: false,
    digitalEyeStrain: false,
    diabetes: true,
    hypertension: false,
    thyroid: false,
    glaucomaHistory: false,
    cataractHistory: false,
    ocularTrauma: false,
    previousSurgery: false,
    existingGlassesPower: "-1.50 DS",
    rightEyeUCDVA: "6/24",
    rightEyeBCDVA: "6/9",
    rightEyePH: "6/12",
    leftEyeUCDVA: "6/18",
    leftEyeBCDVA: "6/6",
    leftEyePH: "6/9",
    rightEyeUCNVA: "N8",
    leftEyeUCNVA: "N6",
    rightEyeSph: -2.0,
    rightEyeCyl: -0.5,
    rightEyeAxis: 180,
    leftEyeSph: -1.5,
    leftEyeCyl: 0,
    leftEyeAxis: 0,
    addPowerRight: 0,
    addPowerLeft: 0,
    muscleFunctionTest: "Normal",
    iop: "16/14 mmHg",
    colorVision: "Normal",
    cupToDiscRatio: "0.3",
    opticDiscPallor: false,
    macularEdema: false,
    amd: false,
    diabeticRetinopathyGrade: "Mild NPDR",
    hypertensiveRetinopathyGrade: "None",
    outcome: "spectacles",
    status: "submitted",
    createdAt: "2026-06-10T09:30:00",
    submittedAt: "2026-06-10T09:45:00",
  },
  {
    id: "emr-002",
    patientId: "pat-002",
    patientName: "Lakshmi Devi",
    campId: "CMP-3401",
    campName: "Mangalagiri PHC Camp",
    screeningTeamId: "TM-12",
    diminishedVisionDistance: false,
    diminishedVisionNear: true,
    redness: false,
    watering: true,
    pain: false,
    blurredVision: false,
    photophobia: false,
    flashersFloaters: false,
    diplopia: false,
    digitalEyeStrain: true,
    diabetes: false,
    hypertension: false,
    thyroid: false,
    glaucomaHistory: false,
    cataractHistory: false,
    ocularTrauma: false,
    previousSurgery: false,
    existingGlassesPower: "",
    rightEyeUCDVA: "6/6",
    rightEyeBCDVA: "6/6",
    rightEyePH: "6/6",
    leftEyeUCDVA: "6/6",
    leftEyeBCDVA: "6/6",
    leftEyePH: "6/6",
    rightEyeUCNVA: "N10",
    leftEyeUCNVA: "N10",
    rightEyeSph: 0,
    rightEyeCyl: 0,
    rightEyeAxis: 0,
    leftEyeSph: 0,
    leftEyeCyl: 0,
    leftEyeAxis: 0,
    addPowerRight: 1.5,
    addPowerLeft: 1.5,
    muscleFunctionTest: "Normal",
    iop: "14/14 mmHg",
    colorVision: "Normal",
    cupToDiscRatio: "0.3",
    opticDiscPallor: false,
    macularEdema: false,
    amd: false,
    diabeticRetinopathyGrade: "None",
    hypertensiveRetinopathyGrade: "None",
    outcome: "spectacles",
    status: "approved",
    createdAt: "2026-06-10T10:15:00",
  },
  {
    id: "emr-003",
    patientId: "pat-003",
    patientName: "Venkat Reddy",
    campId: "CMP-3401",
    campName: "Mangalagiri PHC Camp",
    screeningTeamId: "TM-12",
    screeningTeamName: "Guntur Team Alpha",
    district: "Guntur",
    diminishedVisionDistance: true,
    diminishedVisionNear: true,
    redness: false,
    watering: false,
    pain: false,
    blurredVision: true,
    photophobia: true,
    flashersFloaters: true,
    diplopia: false,
    digitalEyeStrain: false,
    diabetes: true,
    hypertension: true,
    thyroid: false,
    glaucomaHistory: false,
    cataractHistory: true,
    ocularTrauma: false,
    previousSurgery: true,
    existingGlassesPower: "-3.00 DS",
    rightEyeUCDVA: "6/60",
    rightEyeBCDVA: "6/24",
    rightEyePH: "6/36",
    leftEyeUCDVA: "6/36",
    leftEyeBCDVA: "6/12",
    leftEyePH: "6/18",
    rightEyeUCNVA: "N18",
    leftEyeUCNVA: "N12",
    rightEyeSph: -4.0,
    rightEyeCyl: -1.0,
    rightEyeAxis: 90,
    leftEyeSph: -3.5,
    leftEyeCyl: -0.75,
    leftEyeAxis: 85,
    addPowerRight: 2.0,
    addPowerLeft: 2.0,
    muscleFunctionTest: "Restricted",
    iop: "22/20 mmHg",
    colorVision: "Defective",
    cupToDiscRatio: "0.6",
    opticDiscPallor: true,
    macularEdema: true,
    amd: false,
    diabeticRetinopathyGrade: "Moderate NPDR",
    hypertensiveRetinopathyGrade: "Grade 2",
    outcome: "referral",
    status: "submitted",
    createdAt: "2026-06-10T11:00:00",
    submittedAt: "2026-06-10T11:15:00",
  },
  {
    id: "emr-004",
    patientId: "pat-004",
    patientName: "Anjali Kumari",
    campId: "CMP-3402",
    campName: "Tadepalli ZP School",
    screeningTeamId: "TM-13",
    screeningTeamName: "Guntur Team Bravo",
    district: "Guntur",
    diminishedVisionDistance: true,
    diminishedVisionNear: false,
    redness: false,
    watering: false,
    pain: false,
    blurredVision: true,
    photophobia: false,
    flashersFloaters: false,
    diplopia: false,
    digitalEyeStrain: false,
    diabetes: false,
    hypertension: false,
    thyroid: false,
    glaucomaHistory: false,
    cataractHistory: false,
    ocularTrauma: false,
    previousSurgery: false,
    existingGlassesPower: "",
    rightEyeUCDVA: "6/18",
    rightEyeBCDVA: "6/6",
    rightEyePH: "6/6",
    leftEyeUCDVA: "6/24",
    leftEyeBCDVA: "6/6",
    leftEyePH: "6/6",
    rightEyeUCNVA: "N6",
    leftEyeUCNVA: "N6",
    rightEyeSph: -1.5,
    rightEyeCyl: -0.5,
    rightEyeAxis: 90,
    leftEyeSph: -2.0,
    leftEyeCyl: -0.75,
    leftEyeAxis: 85,
    addPowerRight: 0,
    addPowerLeft: 0,
    muscleFunctionTest: "Normal",
    iop: "12/12 mmHg",
    colorVision: "Normal",
    cupToDiscRatio: "0.3",
    opticDiscPallor: false,
    macularEdema: false,
    amd: false,
    diabeticRetinopathyGrade: "None",
    hypertensiveRetinopathyGrade: "None",
    outcome: "spectacles",
    status: "submitted",
    createdAt: "2026-06-11T10:22:00",
    submittedAt: "2026-06-11T10:35:00",
  },
  {
    id: "EMR-50233",
    patientId: "PAT-100237",
    patientName: "Padmavathi",
    campId: "CMP-3401",
    campName: "Mangalagiri PHC Camp",
    screeningTeamId: "TM-12",
    screeningTeamName: "Guntur Team Alpha",
    district: "Guntur",
    diminishedVisionDistance: true,
    diminishedVisionNear: false,
    redness: false,
    watering: false,
    pain: true,
    blurredVision: false,
    photophobia: false,
    flashersFloaters: false,
    diplopia: false,
    digitalEyeStrain: false,
    diabetes: false,
    hypertension: false,
    thyroid: false,
    glaucomaHistory: true,
    cataractHistory: false,
    ocularTrauma: false,
    previousSurgery: false,
    existingGlassesPower: "",
    rightEyeUCDVA: "6/18",
    rightEyeBCDVA: "6/12",
    rightEyePH: "6/9",
    leftEyeUCDVA: "6/24",
    leftEyeBCDVA: "6/12",
    leftEyePH: "6/9",
    rightEyeUCNVA: "N12",
    leftEyeUCNVA: "N12",
    rightEyeSph: 0,
    rightEyeCyl: 0,
    rightEyeAxis: 0,
    leftEyeSph: 0,
    leftEyeCyl: 0,
    leftEyeAxis: 0,
    addPowerRight: 0,
    addPowerLeft: 0,
    muscleFunctionTest: "Normal",
    iop: "26 mmHg",
    colorVision: "Normal",
    cupToDiscRatio: "0.7",
    opticDiscPallor: true,
    macularEdema: false,
    amd: false,
    diabeticRetinopathyGrade: "None",
    hypertensiveRetinopathyGrade: "None",
    outcome: "teleconsult",
    status: "approved",
    nodalOfficerNote:
      "High IOP + CDR 0.7. Glaucoma suspect — teleconsult approved.",
    createdAt: "2026-06-11T09:50:00",
    submittedAt: "2026-06-11T10:05:00",
  },
];

export const spectacleOrders: SpectacleOrder[] = [
  {
    id: "so001",
    patientId: "pat-002",
    patientName: "Lakshmi Devi",
    emrId: "emr-002",
    district: "Guntur",
    vendorId: "v001",
    vendorName: "Vision Optics Hyderabad",
    orderedAt: "2024-06-10",
    status: "Manufacturing",
    expectedDelivery: "2024-06-17",
    slaDays: 7,
    daysElapsed: 2,
    slaBreached: false,
    prescription: {
      rightSph: -2.5,
      rightCyl: -1.0,
      rightAxis: 90,
      rightAdd: 2.0,
      leftSph: -2.25,
      leftCyl: -0.75,
      leftAxis: 85,
      leftAdd: 2.0,
    },
  },
  {
    id: "so002",
    patientId: "pat-003",
    patientName: "Venkat Reddy",
    emrId: "emr-003",
    district: "Visakhapatnam",
    vendorId: "v002",
    vendorName: "Lens Craft Vizag",
    orderedAt: "2024-06-09",
    status: "QA",
    expectedDelivery: "2024-06-16",
    slaDays: 7,
    daysElapsed: 3,
    slaBreached: false,
    prescription: {
      rightSph: -3.5,
      rightCyl: -1.5,
      rightAxis: 180,
      rightAdd: 0,
      leftSph: -3.0,
      leftCyl: -1.25,
      leftAxis: 170,
      leftAdd: 0,
    },
  },
  {
    id: "so003",
    patientId: "pat-004",
    patientName: "Rajamma",
    emrId: "emr-004",
    district: "East Godavari",
    vendorId: "v003",
    vendorName: "EyeCare Rajahmundry",
    orderedAt: "2024-06-06",
    status: "Dispatched",
    expectedDelivery: "2024-06-13",
    slaDays: 7,
    daysElapsed: 6,
    slaBreached: false,
    prescription: {
      rightSph: -1.0,
      rightCyl: -0.5,
      rightAxis: 90,
      rightAdd: 0,
      leftSph: -1.25,
      leftCyl: -0.25,
      leftAxis: 95,
      leftAdd: 0,
    },
  },
  {
    id: "so004",
    patientId: "pat-005",
    patientName: "Narayana Das",
    emrId: "emr-005",
    district: "Kurnool",
    vendorId: "v004",
    vendorName: "OptiKurnool",
    orderedAt: "2024-06-05",
    status: "Delivered",
    expectedDelivery: "2024-06-12",
    actualDelivery: "2024-06-11",
    slaDays: 7,
    daysElapsed: 7,
    slaBreached: false,
    prescription: {
      rightSph: -0.75,
      rightCyl: -0.25,
      rightAxis: 180,
      rightAdd: 0,
      leftSph: -0.5,
      leftCyl: -0.25,
      leftAxis: 175,
      leftAdd: 0,
    },
  },
  {
    id: "so005",
    patientId: "pat-001",
    patientName: "Padma Rao",
    emrId: "emr-001",
    district: "Krishna",
    vendorId: "v002",
    vendorName: "Lens Craft Vizag",
    orderedAt: "2024-06-08",
    status: "Pending",
    expectedDelivery: "2024-06-15",
    slaDays: 7,
    daysElapsed: 4,
    slaBreached: false,
    prescription: {
      rightSph: -1.5,
      rightCyl: -0.5,
      rightAxis: 90,
      rightAdd: 2.0,
      leftSph: -1.5,
      leftCyl: -0.5,
      leftAxis: 85,
      leftAdd: 2.0,
    },
  },
  {
    id: "so006",
    patientId: "pat-002",
    patientName: "Saraswathi",
    emrId: "emr-002",
    district: "Nellore",
    vendorId: "v005",
    vendorName: "VisionCare Nellore",
    orderedAt: "2024-05-28",
    status: "Delivered",
    expectedDelivery: "2024-06-04",
    actualDelivery: "2024-06-05",
    slaDays: 7,
    daysElapsed: 8,
    slaBreached: true,
    prescription: {
      rightSph: -2.0,
      rightCyl: -0.75,
      rightAxis: 90,
      rightAdd: 1.5,
      leftSph: -1.75,
      leftCyl: -0.5,
      leftAxis: 80,
      leftAdd: 1.5,
    },
  },
  {
    id: "so007",
    patientId: "pat-003",
    patientName: "Srinivas Goud",
    emrId: "emr-003",
    district: "Visakhapatnam",
    vendorId: "v002",
    vendorName: "Lens Craft Vizag",
    orderedAt: "2024-06-09",
    status: "Manufacturing",
    expectedDelivery: "2024-06-16",
    slaDays: 7,
    daysElapsed: 3,
    slaBreached: false,
    prescription: {
      rightSph: -1.5,
      rightCyl: -1.0,
      rightAxis: 180,
      rightAdd: 2.5,
      leftSph: -1.25,
      leftCyl: -0.75,
      leftAxis: 175,
      leftAdd: 2.5,
    },
  },
];

export const teleconsultSessions: TeleconsultSession[] = [
  {
    id: "TC-2041",
    patientId: "PAT-100237",
    patientName: "Padmavathi",
    emrId: "EMR-50233",
    ophthalmologistName: "Dr. Suneetha Rao",
    status: "scheduled",
    roomId: "room-tc-2041",
    scheduledAt: "2026-06-11T15:30:00",
    followUpRequired: false,
  },
  {
    id: "tc-001",
    patientId: "pat-003",
    patientName: "Venkat Reddy",
    emrId: "emr-003",
    ophthalmologistName: "Dr. Priya Sharma",
    status: "scheduled",
    roomId: "room-abc123",
    scheduledAt: "2026-06-10T14:00:00",
  },
  {
    id: "tc-002",
    patientId: "pat-001",
    patientName: "Rama Rao",
    emrId: "emr-001",
    ophthalmologistName: "Dr. Rajesh Kumar",
    status: "completed",
    roomId: "room-def456",
    scheduledAt: "2026-06-08T10:00:00",
    clinicalNotes: "Mild DR, advised annual follow-up",
    diagnosis: "Mild Non-Proliferative Diabetic Retinopathy",
    followUpRequired: true,
  },
  {
    id: "ts001",
    patientId: "p001",
    patientName: "Ravi Kumar",
    emrId: "emr-001",
    ophthalmologistName: "Dr. Sridhar Murthy (SVIMS)",
    status: "scheduled",
    roomId: "room-ts001",
    scheduledAt: "2024-06-12T10:00:00",
    followUpRequired: false,
  },
];

export const ophthalmologists = [
  {
    id: "doc001",
    name: "Dr. Sridhar Murthy",
    specialization: "Vitreo-Retina",
    hospital: "SVIMS Tirupati",
    available: true,
    slots: ["09:00", "10:00", "11:00", "14:00", "15:00"],
  },
  {
    id: "doc002",
    name: "Dr. Lalitha Nair",
    specialization: "Glaucoma",
    hospital: "KIMS Hyderabad",
    available: true,
    slots: ["10:00", "11:00", "14:00", "16:00"],
  },
  {
    id: "doc003",
    name: "Dr. Venkata Raman",
    specialization: "Cornea & Refractive",
    hospital: "NTR Trust Vijayawada",
    available: true,
    slots: ["09:00", "10:00", "15:00", "16:00"],
  },
  {
    id: "doc004",
    name: "Dr. Priya Sharma",
    specialization: "Pediatric Ophthalmology",
    hospital: "SVIMS Tirupati",
    available: false,
    slots: [] as string[],
  },
];

export const referrals: Referral[] = [
  {
    id: "r001",
    patientId: "pat-001",
    patientName: "Ravi Kumar",
    emrId: "emr-001",
    emrDate: "2024-06-10",
    priority: "High",
    hospital: "SVIMS Tirupati",
    department: "Ophthalmology Dept",
    condition: "Diabetic Retinopathy Grade I with Macular Edema",
    status: "Appointment Booked",
    appointmentDate: "2024-06-20",
    daysPending: 2,
    district: "Guntur",
  },
  {
    id: "r002",
    patientId: "pat-003",
    patientName: "Venkat Reddy",
    emrId: "emr-003",
    emrDate: "2024-06-09",
    priority: "Critical",
    hospital: "KIMS Vizag",
    department: "Vitreo-Retina",
    condition:
      "Diabetic Retinopathy Moderate + Hypertensive Retinopathy Grade 2",
    status: "Pending",
    daysPending: 3,
    district: "Visakhapatnam",
  },
  {
    id: "r003",
    patientId: "pat-005",
    patientName: "Krishnamurthy",
    emrId: "emr-005",
    emrDate: "2024-06-07",
    priority: "Critical",
    hospital: "SVIMS Tirupati",
    department: "Glaucoma Clinic",
    condition: "Advanced Glaucoma + High IOP (28 mmHg) + Optic Disc Pallor",
    status: "Appointment Booked",
    appointmentDate: "2024-06-14",
    daysPending: 5,
    district: "Chittoor",
  },
  {
    id: "r004",
    patientId: "pat-004",
    patientName: "Ramesh Naidu",
    emrId: "emr-004",
    emrDate: "2024-06-03",
    priority: "High",
    hospital: "GGH Rajam",
    department: "Cataract Clinic",
    condition: "Mature Cataract Right Eye",
    status: "Visited",
    appointmentDate: "2024-06-08",
    daysPending: 0,
    district: "Srikakulam",
  },
  {
    id: "r005",
    patientId: "pat-002",
    patientName: "Srinivas Goud",
    emrId: "emr-002",
    emrDate: "2024-06-09",
    priority: "Routine",
    hospital: "KIMS Vizag",
    department: "Ophthalmology",
    condition: "Posterior Vitreous Detachment Evaluation",
    status: "Pending",
    daysPending: 3,
    district: "Visakhapatnam",
  },
];

export const vendors: Vendor[] = [
  {
    id: "v001",
    name: "Vision Optics Hyderabad",
    location: "Hyderabad",
    contact: "040-23456789",
    email: "ops@visionoptics.in",
    orders: 1245,
    delivered: 1198,
    slaPct: 96.2,
    breaches: 47,
    rating: 4.5,
    status: "active",
    onboardedDate: "2023-01-15",
  },
  {
    id: "v002",
    name: "Lens Craft Vizag",
    location: "Visakhapatnam",
    contact: "0891-2345678",
    email: "lenscraft@vizag.in",
    orders: 987,
    delivered: 934,
    slaPct: 94.6,
    breaches: 53,
    rating: 4.2,
    status: "active",
    onboardedDate: "2023-03-20",
  },
  {
    id: "v003",
    name: "EyeCare Rajahmundry",
    location: "Rajahmundry",
    contact: "0883-2345678",
    email: "eyecare@rjy.in",
    orders: 756,
    delivered: 710,
    slaPct: 93.9,
    breaches: 46,
    rating: 4.0,
    status: "active",
    onboardedDate: "2023-02-10",
  },
  {
    id: "v004",
    name: "OptiKurnool",
    location: "Kurnool",
    contact: "08518-234567",
    email: "opti@kurnool.in",
    orders: 534,
    delivered: 498,
    slaPct: 93.3,
    breaches: 36,
    rating: 3.9,
    status: "active",
    onboardedDate: "2023-05-01",
  },
  {
    id: "v005",
    name: "VisionCare Nellore",
    location: "Nellore",
    contact: "0861-2345678",
    email: "vc@nellore.in",
    orders: 612,
    delivered: 567,
    slaPct: 92.6,
    breaches: 45,
    rating: 3.7,
    status: "active",
    onboardedDate: "2023-04-15",
  },
];

export const users: User[] = [
  {
    id: "u001",
    name: "Admin Suresh",
    email: "suresh.admin@apvision.gov.in",
    mobile: "9000000001",
    role: "super_admin",
    district: "All",
    status: "active",
    lastLogin: "2024-06-10T08:00:00",
  },
  {
    id: "u002",
    name: "Ramakrishna Murthy",
    email: "ramakrishna.no@apvision.gov.in",
    mobile: "9000000002",
    role: "nodal_officer",
    district: "Guntur",
    status: "active",
    lastLogin: "2024-06-10T08:30:00",
  },
  {
    id: "u003",
    name: "Venkateswara Rao",
    email: "venkat.no@apvision.gov.in",
    mobile: "9000000003",
    role: "nodal_officer",
    district: "Visakhapatnam",
    status: "active",
    lastLogin: "2024-06-09T09:00:00",
  },
  {
    id: "u004",
    name: "Dr. Prasad Kumar",
    email: "prasad.opt@apvision.gov.in",
    mobile: "9000000004",
    role: "screening_team",
    district: "Guntur",
    status: "active",
    lastLogin: "2024-06-10T09:00:00",
  },
  {
    id: "u005",
    name: "Dr. Sunitha Rao",
    email: "sunitha.opt@apvision.gov.in",
    mobile: "9000000005",
    role: "screening_team",
    district: "Krishna",
    status: "active",
    lastLogin: "2024-06-09T09:30:00",
  },
  {
    id: "u006",
    name: "Dr. Hari Prasad",
    email: "hari.opt@apvision.gov.in",
    mobile: "9000000006",
    role: "screening_team",
    district: "Chittoor",
    status: "active",
    lastLogin: "2024-06-07T08:45:00",
  },
  {
    id: "u007",
    name: "Dr. Kavitha Reddy",
    email: "kavitha.opt@apvision.gov.in",
    mobile: "9000000007",
    role: "screening_team",
    district: "East Godavari",
    status: "active",
    lastLogin: "2024-06-06T09:00:00",
  },
  {
    id: "u008",
    name: "Dr. Mohan Rao",
    email: "mohan.opt@apvision.gov.in",
    mobile: "9000000008",
    role: "screening_team",
    district: "Kurnool",
    status: "active",
    lastLogin: "2024-06-05T08:30:00",
  },
  {
    id: "u009",
    name: "Dr. Geetha Krishnan",
    email: "geetha.opt@apvision.gov.in",
    mobile: "9000000009",
    role: "screening_team",
    district: "Krishna",
    status: "active",
    lastLogin: "2024-06-08T09:00:00",
  },
  {
    id: "u010",
    name: "Srinivasa Reddy",
    email: "srinivasa.no@apvision.gov.in",
    mobile: "9000000010",
    role: "nodal_officer",
    district: "Chittoor",
    status: "active",
    lastLogin: "2024-06-07T08:00:00",
  },
  {
    id: "u011",
    name: "Ranga Rao",
    email: "ranga.no@apvision.gov.in",
    mobile: "9000000011",
    role: "nodal_officer",
    district: "East Godavari",
    status: "active",
    lastLogin: "2024-06-06T08:30:00",
  },
  {
    id: "u012",
    name: "Krishna Murthy",
    email: "krishna.no@apvision.gov.in",
    mobile: "9000000012",
    role: "nodal_officer",
    district: "Kurnool",
    status: "active",
    lastLogin: "2024-06-05T09:00:00",
  },
  {
    id: "u013",
    name: "Padmanabha Rao",
    email: "padma.no@apvision.gov.in",
    mobile: "9000000013",
    role: "nodal_officer",
    district: "Nellore",
    status: "active",
    lastLogin: "2024-06-04T09:00:00",
  },
  {
    id: "u014",
    name: "Anand Kumar",
    email: "anand.no@apvision.gov.in",
    mobile: "9000000014",
    role: "nodal_officer",
    district: "West Godavari",
    status: "inactive",
    lastLogin: "2024-05-30T09:00:00",
  },
  {
    id: "u015",
    name: "Babu Rao",
    email: "babu.no@apvision.gov.in",
    mobile: "9000000015",
    role: "nodal_officer",
    district: "Srikakulam",
    status: "active",
    lastLogin: "2024-06-03T08:30:00",
  },
  {
    id: "u016",
    name: "Venkat Rao",
    email: "venkat2.no@apvision.gov.in",
    mobile: "9000000016",
    role: "nodal_officer",
    district: "Vizianagaram",
    status: "active",
    lastLogin: "2024-06-09T09:30:00",
  },
  {
    id: "u017",
    name: "Dr. Venkata Rao",
    email: "venkata.opt@apvision.gov.in",
    mobile: "9000000017",
    role: "screening_team",
    district: "Visakhapatnam",
    status: "active",
    lastLogin: "2024-06-09T08:00:00",
  },
  {
    id: "u018",
    name: "Dr. Babu Rao",
    email: "babu.opt@apvision.gov.in",
    mobile: "9000000018",
    role: "screening_team",
    district: "Srikakulam",
    status: "active",
    lastLogin: "2024-06-03T08:45:00",
  },
  {
    id: "u019",
    name: "Ravi Kumar",
    email: "ravi.kumar@gmail.com",
    mobile: "9876543210",
    role: "patient",
    district: "Guntur",
    status: "active",
    lastLogin: "2024-06-10T10:00:00",
  },
  {
    id: "u020",
    name: "Lakshmi Devi",
    email: "lakshmi.devi@gmail.com",
    mobile: "9876543211",
    role: "patient",
    district: "Guntur",
    status: "active",
    lastLogin: "2024-06-10T11:00:00",
  },
];

export const auditLogs: AuditLog[] = [
  {
    id: "AL-99001",
    entityType: "EMR",
    entityId: "EMR-50233",
    action: "APPROVE",
    performedBy: "Sri K. Venkateswarlu",
    performedByRole: "nodal_officer",
    ipAddress: "10.4.22.18",
    timestamp: "2026-06-11T10:06:00",
    summary: "Approved EMR for teleconsult outcome",
  },
  {
    id: "AL-99000",
    entityType: "EMR",
    entityId: "EMR-50232",
    action: "SUBMIT",
    performedBy: "M. Lakshmi",
    performedByRole: "screening_team",
    ipAddress: "10.9.4.55",
    timestamp: "2026-06-11T09:40:00",
    summary: "Submitted EMR with referral outcome",
  },
  {
    id: "AL-98999",
    entityType: "Patient",
    entityId: "PAT-100241",
    action: "CREATE",
    performedBy: "M. Lakshmi",
    performedByRole: "screening_team",
    ipAddress: "10.9.4.55",
    timestamp: "2026-06-11T10:48:00",
    summary: "Registered new patient via QR scan-and-share",
  },
  {
    id: "AL-98998",
    entityType: "SpectacleOrder",
    entityId: "SO-70011",
    action: "CREATE",
    performedBy: "System",
    performedByRole: "system",
    ipAddress: "127.0.0.1",
    timestamp: "2026-06-11T09:15:00",
    summary: "Auto-created spectacle order from approved prescription",
  },
  {
    id: "AL-98995",
    entityType: "Vendor",
    entityId: "V-06",
    action: "SUSPEND",
    performedBy: "Dr. Anitha Rao",
    performedByRole: "super_admin",
    ipAddress: "10.1.1.2",
    timestamp: "2026-06-10T17:20:00",
    summary: "Suspended vendor for repeated SLA breaches (38)",
  },
  {
    id: "AL-98990",
    entityType: "TeleconsultSession",
    entityId: "TC-2039",
    action: "COMPLETE",
    performedBy: "Dr. Suneetha Rao",
    performedByRole: "tele_ophthalmologist",
    ipAddress: "10.7.3.41",
    timestamp: "2026-06-10T11:21:00",
    summary: "Completed teleconsult, diagnosis recorded",
  },
  {
    id: "AL-98985",
    entityType: "Referral",
    entityId: "REF-8795",
    action: "SCHEDULE",
    performedBy: "Sri K. Venkateswarlu",
    performedByRole: "nodal_officer",
    ipAddress: "10.4.22.18",
    timestamp: "2026-06-10T12:30:00",
    summary: "Scheduled critical referral at King George Hospital",
  },
  {
    id: "AL-98980",
    entityType: "SpectacleOrder",
    entityId: "SO-70005",
    action: "SLA_BREACH",
    performedBy: "System",
    performedByRole: "system",
    ipAddress: "127.0.0.1",
    timestamp: "2026-06-09T10:00:00",
    summary: "SLA deadline crossed — nodal officer alerted",
  },
  {
    id: "AL-98975",
    entityType: "ABHA",
    entityId: "PAT-100234",
    action: "CARE_CONTEXT_LINK",
    performedBy: "System",
    performedByRole: "system",
    ipAddress: "127.0.0.1",
    timestamp: "2026-06-11T09:12:00",
    summary: "Linked APVC-EMR-50231 care context to ABHA",
  },
];

export const screeningTeams: ScreeningTeam[] = [
  {
    id: "TM-12",
    name: "Guntur Team Alpha",
    district: "Guntur",
    mandal: "Mangalagiri",
    leadName: "M. Lakshmi (Optometrist)",
    members: [
      { name: "M. Lakshmi", role: "Optometrist" },
      { name: "K. Ramesh", role: "Ophthalmic Assistant" },
      { name: "S. Devi", role: "Data Entry Operator" },
    ],
    assignedCampId: "CMP-3401",
    assignedCampName: "Mangalagiri PHC Camp",
    patientsScreenedToday: 112,
    status: "active",
  },
  {
    id: "TM-13",
    name: "Guntur Team Bravo",
    district: "Guntur",
    mandal: "Tadepalli",
    leadName: "P. Srinivas (Optometrist)",
    members: [
      { name: "P. Srinivas", role: "Optometrist" },
      { name: "A. Kumar", role: "Ophthalmic Assistant" },
    ],
    assignedCampId: "CMP-3402",
    assignedCampName: "Tadepalli ZP School",
    patientsScreenedToday: 95,
    status: "active",
  },
  {
    id: "TM-14",
    name: "Guntur Team Charlie",
    district: "Guntur",
    mandal: "Ponnur",
    leadName: "R. Swathi (Optometrist)",
    members: [
      { name: "R. Swathi", role: "Optometrist" },
      { name: "T. Naidu", role: "Ophthalmic Assistant" },
    ],
    patientsScreenedToday: 0,
    status: "idle",
  },
  {
    id: "TM-15",
    name: "Guntur Team Delta",
    district: "Guntur",
    mandal: "Bapatla",
    leadName: "J. Prasad (Optometrist)",
    members: [
      { name: "J. Prasad", role: "Optometrist" },
      { name: "L. Reddy", role: "Data Entry Operator" },
    ],
    patientsScreenedToday: 0,
    status: "offline",
  },
];

export const governmentReports = [
  {
    id: "rpt-001",
    name: "Monthly Screening Report - May 2026",
    type: "Monthly",
    generatedAt: "2026-06-01",
    size: "2.4 MB",
  },
  {
    id: "rpt-002",
    name: "District Performance - Q1 2026",
    type: "Quarterly",
    generatedAt: "2026-04-05",
    size: "5.1 MB",
  },
  {
    id: "rpt-003",
    name: "Spectacle Delivery SLA Report",
    type: "SLA",
    generatedAt: "2026-06-08",
    size: "1.2 MB",
  },
  {
    id: "rpt-004",
    name: "ABDM Integration Status Report",
    type: "Compliance",
    generatedAt: "2026-06-09",
    size: "890 KB",
  },
];

export const aiHotspots: AIHotspot[] = [
  {
    district: "Guntur",
    burdenScore: 78,
    drPrevalence: 12.4,
    cataractRisk: 18.2,
    glaucomaRisk: 4.3,
    refractiveError: 35.6,
    predictedDemand: 4800,
    riskLevel: "High",
  },
  {
    district: "Visakhapatnam",
    burdenScore: 74,
    drPrevalence: 11.3,
    cataractRisk: 16.8,
    glaucomaRisk: 3.9,
    refractiveError: 33.2,
    predictedDemand: 4200,
    riskLevel: "High",
  },
  {
    district: "Krishna",
    burdenScore: 73,
    drPrevalence: 11.7,
    cataractRisk: 17.1,
    glaucomaRisk: 4.1,
    refractiveError: 34.5,
    predictedDemand: 4000,
    riskLevel: "High",
  },
  {
    district: "East Godavari",
    burdenScore: 71,
    drPrevalence: 10.8,
    cataractRisk: 15.9,
    glaucomaRisk: 3.7,
    refractiveError: 32.8,
    predictedDemand: 3800,
    riskLevel: "Moderate",
  },
  {
    district: "West Godavari",
    burdenScore: 68,
    drPrevalence: 10.2,
    cataractRisk: 15.2,
    glaucomaRisk: 3.5,
    refractiveError: 31.4,
    predictedDemand: 3500,
    riskLevel: "Moderate",
  },
  {
    district: "Anantapur",
    burdenScore: 67,
    drPrevalence: 9.3,
    cataractRisk: 14.8,
    glaucomaRisk: 3.2,
    refractiveError: 30.2,
    predictedDemand: 3200,
    riskLevel: "Moderate",
  },
  {
    district: "Vizianagaram",
    burdenScore: 65,
    drPrevalence: 9.1,
    cataractRisk: 14.3,
    glaucomaRisk: 3.0,
    refractiveError: 29.8,
    predictedDemand: 2900,
    riskLevel: "Moderate",
  },
  {
    district: "Nellore",
    burdenScore: 69,
    drPrevalence: 10.1,
    cataractRisk: 15.0,
    glaucomaRisk: 3.6,
    refractiveError: 31.8,
    predictedDemand: 3400,
    riskLevel: "Moderate",
  },
  {
    district: "Kurnool",
    burdenScore: 64,
    drPrevalence: 8.9,
    cataractRisk: 13.9,
    glaucomaRisk: 2.9,
    refractiveError: 29.1,
    predictedDemand: 2800,
    riskLevel: "Moderate",
  },
  {
    district: "Prakasam",
    burdenScore: 66,
    drPrevalence: 9.6,
    cataractRisk: 14.6,
    glaucomaRisk: 3.1,
    refractiveError: 30.8,
    predictedDemand: 3100,
    riskLevel: "Moderate",
  },
  {
    district: "Kadapa",
    burdenScore: 63,
    drPrevalence: 8.5,
    cataractRisk: 13.4,
    glaucomaRisk: 2.7,
    refractiveError: 28.4,
    predictedDemand: 2600,
    riskLevel: "Low",
  },
  {
    district: "Srikakulam",
    burdenScore: 62,
    drPrevalence: 8.2,
    cataractRisk: 13.1,
    glaucomaRisk: 2.6,
    refractiveError: 27.9,
    predictedDemand: 2500,
    riskLevel: "Low",
  },
  {
    district: "Chittoor",
    burdenScore: 60,
    drPrevalence: 8.0,
    cataractRisk: 12.8,
    glaucomaRisk: 2.5,
    refractiveError: 27.2,
    predictedDemand: 2300,
    riskLevel: "Low",
  },
];

export const demandForecast = [
  { month: "Jul 2024", predicted: 4200, lower: 3800, upper: 4600 },
  { month: "Aug 2024", predicted: 4500, lower: 4100, upper: 4900 },
  { month: "Sep 2024", predicted: 4800, lower: 4400, upper: 5200 },
];

export const referralPriorities: ReferralPriority[] = [
  {
    id: "r001",
    patientName: "Ravi Kumar",
    district: "Guntur",
    condition: "Diabetic Retinopathy Grade I with Macular Edema",
    hospital: "SVIMS Tirupati",
    priority: "High",
    daysPending: 2,
    status: "Appointment Booked",
  },
  {
    id: "r002",
    patientName: "Venkat Reddy",
    district: "Visakhapatnam",
    condition:
      "Diabetic Retinopathy Moderate + Hypertensive Retinopathy Grade 2",
    hospital: "KIMS Vizag",
    priority: "Critical",
    daysPending: 3,
    status: "Pending",
  },
  {
    id: "r003",
    patientName: "Krishnamurthy",
    district: "Chittoor",
    condition: "Advanced Glaucoma + High IOP (28 mmHg) + Optic Disc Pallor",
    hospital: "SVIMS Tirupati",
    priority: "Critical",
    daysPending: 5,
    status: "Appointment Booked",
  },
  {
    id: "r004",
    patientName: "Ramesh Naidu",
    district: "Srikakulam",
    condition: "Mature Cataract Right Eye",
    hospital: "GGH Rajam",
    priority: "High",
    daysPending: 0,
    status: "Visited",
  },
  {
    id: "r005",
    patientName: "Srinivas Goud",
    district: "Visakhapatnam",
    condition: "Posterior Vitreous Detachment Evaluation",
    hospital: "KIMS Vizag",
    priority: "Routine",
    daysPending: 3,
    status: "Pending",
  },
];

const patientRaviKumar = patients.find((p) => p.id === "p001")!;

export const patientPortalData = {
  patient: patientRaviKumar,
  prescriptions: [
    {
      id: "rx001",
      date: "June 10, 2024",
      camp: "Narasaraopet Village Camp",
      optometrist: "Dr. Prasad Kumar",
      rightEye: { sph: -2.0, cyl: -0.5, axis: 180, add: 1.5 },
      leftEye: { sph: -1.75, cyl: -0.25, axis: 175, add: 1.5 },
      note: "Bifocal lenses recommended for near and distance vision",
      outcome: "Referral" as const,
    },
  ],
  spectacleOrder: spectacleOrders[1],
  referral: referrals.find((r) => r.id === "r001") ?? null,
  teleconsult: teleconsultSessions[1],
  visitHistory: [
    {
      date: "2024-06-10",
      camp: "Narasaraopet Village Camp",
      outcome: "Referral",
      status: "Appointment Booked",
    },
    {
      date: "2025-12-15",
      camp: "Mangalagiri PHC Camp",
      outcome: "Spectacles prescribed",
      status: "Delivered",
    },
    {
      date: "2024-08-20",
      camp: "Narasaraopet Village Camp",
      outcome: "Normal",
      status: "Completed",
    },
  ],
};

export function getPatientById(id: string) {
  return patients.find((p) => p.id === id);
}

export function getEMRByPatientId(patientId: string) {
  return emrs.find((e) => e.patientId === patientId);
}

export function getDistrictKPI(district: string) {
  return districtKPIs.find((d) => d.district === district);
}
